name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  TERRAFORM_VERSION: 1.11.0
  DEV_TERRAFORM_ROLE: arn:aws:iam::937168356724:role/GitHubActions
  PROD_TERRAFORM_ROLE: arn:aws:iam::730335516527:role/GitHubActions

jobs:
  ci:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform-version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform TfLint
        uses: terraform-linters/setup-tflint@v4.1.1
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run Terraform Init
        working-directory: terraform
        run: terraform init -backend=false

      - name: Terraform Providers Lock Check
        working-directory: terraform
        run: |
          terraform providers lock \
          -platform=linux_amd64 \
          -platform=darwin_amd64 \
          -platform=darwin_arm64

          if ! git ls-files --error-unmatch .terraform.lock.hcl >/dev/null 2>&1; then
            echo "The .terraform.lock.hcl file is missing!"
            echo "Please add the lock file and commit the changes."
            exit 1
          fi

          if git diff --exit-code .terraform.lock.hcl; then
            echo "No changes to .terraform.lock.hcl"
          else
            echo "There are changes in the .terraform.lock.hcl"
            echo "Please update the lock file with and commit the changes."
            exit 1
          fi

      - name: Run Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Trivy Security Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          working-directory: terraform
          format: table
          scan-type: config
          severity: CRITICAL,HIGH
          fail-on-diff: false
          output: trivy-result.txt

      - name: Format Trivy Scan Result
        run: |
          cat trivy-result.txt
          if [ -s trivy-result.txt ]; then
            echo -e "## Vulnerability Scan Results\n<details><summary>Details</summary>\n\n\`\`\`\n$(cat trivy-result.txt)\n\`\`\`\n</details>" > trivy-result.txt
            echo "vulnerabilities=true" >> $GITHUB_ENV
          else
            echo "vulnerabilities=false" >> $GITHUB_ENV
          fi

      - name: Comment PR with Trivy scan results
        if: env.vulnerabilities == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-result.txt

      - name: Remove PR Comment if No Issues Found
        if: env.vulnerabilities == 'false'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: true

      - name: Fail if Vulnerabilities Exist
        if: env.vulnerabilities == 'true'
        run: |
          echo "Vulnerabilities were found. Please fix it following commits."
          exit 1

      - name: Terraform TfLint
        working-directory: terraform
        run: |
          tflint --init
          tflint --recursive

      - name: Terraform docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: terraform
          config-file: .terraform-docs.yml
          git-push: true
          # fail-on-diff: true

      - name: Check git diff
        run: |
          git diff terraform/README.md

  plan-dev-us-east-1:
    name: "[DEV - us-east-1] Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Plan
        uses: ./.github/actions/terraform
        with:
          action: plan
          environment: DEV
          aws_region: us-east-1
          tfconfig_path: config/dev/us-east-1.hcl
          tfvars_path: vars/dev/us-east-1.tfvars
          aws_role_arn: ${{ env.DEV_TERRAFORM_ROLE }}
          github_token: ${{ github.token }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}

  apply-dev-us-east-1:
    needs:
      - plan-dev-us-east-1
    name: "[DEV - us-east-1] Terraform Apply"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Apply
        uses: ./.github/actions/terraform
        with:
          action: apply
          environment: DEV
          aws_region: us-east-1
          tfconfig_path: config/dev/us-east-1.hcl
          tfvars_path: vars/dev/us-east-1.tfvars
          aws_role_arn: ${{ env.DEV_TERRAFORM_ROLE }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}

  plan-prod-us-east-1:
    name: "[PROD - us-east-1] Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Plan
        uses: ./.github/actions/terraform
        with:
          action: plan
          environment: PROD
          aws_region: us-east-1
          tfconfig_path: config/prod/us-east-1.hcl
          tfvars_path: vars/prod/us-east-1.tfvars
          aws_role_arn: ${{ env.PROD_TERRAFORM_ROLE }}
          github_token: ${{ github.token }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}

  apply-prod-us-east-1:
    needs:
      - apply-dev-us-east-1
      - plan-prod-us-east-1
    name: "[PROD - us-east-1] Terraform Apply"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Apply
        uses: ./.github/actions/terraform
        with:
          action: apply
          environment: PROD
          aws_region: us-east-1
          tfconfig_path: config/prod/us-east-1.hcl
          tfvars_path: vars/prod/us-east-1.tfvars
          aws_role_arn: ${{ env.PROD_TERRAFORM_ROLE }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
